title:         David Martinez Peña
description:   Pàgina web oficial
baseurl:       "martinezpenya.es"
url:           "www.martinezpenya.es"

# Build settings
#markdown:      kramdown
#paginate:      5
#paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate